version: "3.9"
services:
  validator:
    image: arashidos/lava-cosmovisor:v0.23.5
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "start-node"
    ports:
      - "${PORT_RPC}:26657"
      - "${PORT_PEER}:26656"
      - "${PORT_API}:1317"
      - "${PORT_GRPC}:9090"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      lava:
    volumes:
      - ./helpers.sh:/opt/helpers.sh
      - lava:/root/.lava
  lavavisor:
    image: arashidos/lava-cosmovisor:v0.23.5
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "update-lavap-version"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    volumes:
      - ./helpers.sh:/opt/helpers.sh
      - lava_binaries:/go/bin
volumes:
  lava:
    external: true
    name: lava
  lava_binaries:
    external: true
    name: lava_binaries
networks:
  lava:
    external: true
    name: lava