version: "3.9"
services:
  validator:
    build:
      dockerfile: docker/Dockerfile
      context: docker/.
      args:
       - CONFIG_REPO_URL=${CONFIG_REPO_URL:-https://github.com/lavanet/lava-config.git}
       - CONFIG_REPO_PATH=${CONFIG_REPO_PATH:-lava-config/testnet-2}
       - LAVA_REPO_URL=${LAVA_REPO_URL:-https://github.com/lavanet/lava.git}
       - LAVA_REPO_TAG=${LAVA_REPO_TAG:-v0.32.0}

    image: ${LAVA_IMAGE:-arashidos/lava:v0.32.0}
    env_file:
      - .env
    restart: unless-stopped
    command:
      - "start-node"
    ports:
      - "${PORT_RPC}:26657"
      - "${PORT_PEER}:26656"
      - "${PORT_API}:1317"
      - "${PORT_GRPC}:9090"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      lava:
    volumes:
      - lava:/root/.lava
volumes:
  lava:
    external: true
    name: lava
networks:
  lava:
    external: true
    name: lava