version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    networks:
      - public
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    labels:
      - "traefik.enable=true"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
  public:
    external: true
