version: '3.9'

services:
  traefik:
    image: traefik:v2.9.6
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - public
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dash.${TRAEFIK_ROOT_DOMAIN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      - "traefik.http.routers.api.middlewares=traefik-auth"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certResolver=httpresolver"
      - "traefik.http.routers.api.tls.domains[0].main=${TRAEFIK_ROOT_DOMAIN}"
      - "traefik.http.routers.api.tls.domains[0].sans=*.${TRAEFIK_ROOT_DOMAIN}"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
networks:
  public:
    external: true
